[package]
categories = ["cryptography"]
description = "Tectonic's common cryptography library"
documentation = "https://docs.rs/bedrock"
edition = "2024"
keywords = ["post-quantum"]
name = "bedrock"
readme = "README.md"
repository = "https://github.com/tectonic-labs/bedrock"
version = "0.1.0"

[features]
default = ["eth_falcon", "kgen", "sign", "vrfy"]
eth_falcon = ["rand_chacha", "rand_core", "fn-dsa-comm/eth_falcon", "fn-dsa-sign?/eth_falcon", "fn-dsa-vrfy?/eth_falcon", "zeroize"]
kgen = ["fn-dsa-comm", "fn-dsa-kgen", "rand_core?/getrandom"]
sign = ["fn-dsa-comm", "fn-dsa-sign"]
vrfy = ["fn-dsa-comm", "fn-dsa-vrfy"]

[dependencies]
hex = "0.4"
rand_chacha = { version = "0.3", optional = true }
rand_core = { version = "0.6", optional = true }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
zeroize = { version = "1.8", optional = true }

[dependencies.oqs]
git = "https://github.com/tectonic-labs/liboqs-rust"
tag = "tectonic/0.11.0-falcon-padded-dev5"
default-features = false
features = [
    "falcon",
    "serde",
    "zeroize",
]

[dependencies.fn-dsa-comm]
git = "https://github.com/tectonic-labs/rust-fn-dsa"
tag = "tectonic/0.3.0"
optional = true

[dependencies.fn-dsa-kgen]
git = "https://github.com/tectonic-labs/rust-fn-dsa"
tag = "tectonic/0.3.0"
optional = true

[dependencies.fn-dsa-sign]
git = "https://github.com/tectonic-labs/rust-fn-dsa"
tag = "tectonic/0.3.0"
optional = true

[dependencies.fn-dsa-vrfy]
git = "https://github.com/tectonic-labs/rust-fn-dsa"
tag = "tectonic/0.3.0"
optional = true

[dev-dependencies.fn-dsa]
git = "https://github.com/tectonic-labs/rust-fn-dsa"
tag = "tectonic/0.3.0"

[dev-dependencies]
falcon-rust = "0.1.2"
postcard = {  version = "1.0", features = ["use-std"] }
pqcrypto = { version = "0.18", default-features = false, features = ["pqcrypto-falcon"] }
rand = "0.8"
rand_chacha = "0.3"
serde_json = "1.0"

[lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused = "warn"

[lints.clippy]
mod_module_files = "deny"
unwrap_used = "deny"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]