[package]
categories = ["cryptography"]
description = "Tectonic's common cryptography library"
documentation = "https://docs.rs/bedrock"
edition = "2024"
keywords = ["post-quantum"]
name = "bedrock"
readme = "README.md"
repository = "https://github.com/tectonic-labs/bedrock"
version = "0.1.0"

[features]
default = ["kgen", "sign", "vrfy"]
kgen = []
sign = []
vrfy = []

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[dependencies.oqs]
git = "https://github.com/tectonic-labs/liboqs-rust"
tag = "tectonic/0.11.0-falcon-padded-dev3"
default-features = false
features = [
    "falcon"
]

[dev-dependencies]
falcon-rust = "0.1.2"
fn-dsa = "0.3.0"
postcard = {  version = "1.0", features = ["use-std"] }
pqcrypto = { version = "0.18", default-features = false, features = ["pqcrypto-falcon"] }
rand = "0.8"
rand_chacha = "0.3"
serde_json = "1.0"

[lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused = "warn"

[lints.clippy]
mod_module_files = "deny"
unwrap_used = "deny"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]